spring:
  application:
    name: elimuconnect-backend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
