spring:
  application:
    name: elimuconnect-backend
  
  data:
    mongodb:
      uri: ${DATABASE_URL}
      auto-index-creation: false
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    enabled-by-default: false
  health:
    enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  
  client:
    url: ${CLIENT_URL}

logging:
  level:
    ke.elimuconnect: INFO
