spring:
  application:
    name: ElimuConnect Backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/elimuconnect}
      database: ${MONGODB_DATABASE:elimuconnect}
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:elimuconnect-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    email: ${ADMIN_EMAIL:manodhiambo@gmail.com}
    phone: ${ADMIN_PHONE:0703445756}
  upload:
    dir: ${UPLOAD_DIR:${user.home}/elimuconnect-uploads}
    max-file-size: 100MB
    max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
